// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIzHzsF45xz9tbkjyx7ye_JhWcZ_Vzkf0',
    appId: '1:349280234307:web:cb5ccbe6779b41eebe5df6',
    messagingSenderId: '349280234307',
    projectId: 'capsulea-c23ab',
    authDomain: 'capsulea-c23ab.firebaseapp.com',
    storageBucket: 'capsulea-c23ab.firebasestorage.app',
    measurementId: 'G-CGFGZYWL2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5LlhU3F0kTBRxb6srKtWI6yD5LNorObk',
    appId: '1:349280234307:android:6ba6ce51c247060dbe5df6',
    messagingSenderId: '349280234307',
    projectId: 'capsulea-c23ab',
    storageBucket: 'capsulea-c23ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcYzlvEUJv3Qhhx4CzyTPmqTSqu0txFto',
    appId: '1:349280234307:ios:7d2934c9398bf1b8be5df6',
    messagingSenderId: '349280234307',
    projectId: 'capsulea-c23ab',
    storageBucket: 'capsulea-c23ab.firebasestorage.app',
    androidClientId: '349280234307-6s3jprvnuuql91qbkklms5rd88di8mvm.apps.googleusercontent.com',
    iosClientId: '349280234307-4qvgfjlt2l0k0adb1ko14dvp64allo26.apps.googleusercontent.com',
    iosBundleId: 'com.example.capsuleaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcYzlvEUJv3Qhhx4CzyTPmqTSqu0txFto',
    appId: '1:349280234307:ios:7d2934c9398bf1b8be5df6',
    messagingSenderId: '349280234307',
    projectId: 'capsulea-c23ab',
    storageBucket: 'capsulea-c23ab.firebasestorage.app',
    androidClientId: '349280234307-6s3jprvnuuql91qbkklms5rd88di8mvm.apps.googleusercontent.com',
    iosClientId: '349280234307-4qvgfjlt2l0k0adb1ko14dvp64allo26.apps.googleusercontent.com',
    iosBundleId: 'com.example.capsuleaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIzHzsF45xz9tbkjyx7ye_JhWcZ_Vzkf0',
    appId: '1:349280234307:web:506075b62aa50915be5df6',
    messagingSenderId: '349280234307',
    projectId: 'capsulea-c23ab',
    authDomain: 'capsulea-c23ab.firebaseapp.com',
    storageBucket: 'capsulea-c23ab.firebasestorage.app',
    measurementId: 'G-7028DCF21T',
  );
}
